### ISSUE TITLE
Can you support Node v4.8.1 ?

### ISSUE THREAD

**Issue by sheeeeep** [jonathantneal/postcss-write-svg#20]
Sorry for this request.

module.exports = postcss.plugin('postcss-place', ({
                                                  ^
ReferenceError: Invalid left-hand side in assignment
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)

**Comment by jonathantneal** [comment]
This is very reasonable. I’ll put it on my todo for this weekend.

**Comment by jonathantneal** [comment]
I never did this, huh. And now Node 4 is no longer supported. I’m sorry for forgetting this.
